server:
    tomcat:
      uri-encoding: utf-8
    port: 8083
    ssl:
      key-alias: tomcat_key
      keyStoreType: JKS
      key-store: server.keystore
      key-store-password: changeit

spring:
    datasource:
      url: jdbc:mysql://172.16.1.204:3306/test2
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver

    jpa:
      database: mysql
      show-sql: true
      hibernate:
        ddl-auto: update
      properties:
         hibernate:
            dialect: org.hibernate.dialect.MySQL5Dialect
            enable_lazy_load_no_trans: true

    thymeleaf:
      cache: false
      check-template: true
      check-template-location: true
      prefix: classpath:/templates/
      suffix: .html
      encoding: UTF-8
      mode: HTML5
      servlet:
        content-type: text/html

    devtools:
       restart:
          exclude: static/**,public/**
